version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 9080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/html:/usr/share/nginx/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      ./docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 9081:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb

  composer:
    image: composer:1.6
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: composer install